#https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build
#https://cloud.google.com/run/docs/deploying#service
---
  steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      git config -f .gitmodules submodule.common.url https://source.developers.google.com/p/rocketsidekick/r/github_thzero_rocket_sidekick-common
      git submodule init
      git submodule update
  - name: "docker:stable"
    args:
    - "build"
    - "-t"
    - "gcr.io/$PROJECT_ID/api:$COMMIT_SHA"
    - "."
  - name: "docker:stable"
    args:
    - "push"
    - "gcr.io/$PROJECT_ID/api:$COMMIT_SHA"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
    - "run"
    - "deploy"
    - "api"
    - "--image"
    - "gcr.io/$PROJECT_ID/api:$COMMIT_SHA"
    - "--region"
    - "us-central1"
    - "--platform"
    - "managed"
  images:
  - "gcr.io/$PROJECT_ID/api:$COMMIT_SHA"
